In [2]:
import numpy as np

In [2]:
b = np.array([[1.0, 2.0, 3.0 ],[3.0, 4.0, 5.0]])

In [3]:
print(b)

[[1. 2. 3.]
 [3. 4. 5.]]


In [4]:
np.size

<function numpy.size(a, axis=None)>

In [5]:
b.size

6

In [6]:
b.shape

(2, 3)

In [7]:
b.ndim

2

In [8]:
b.itemsize

8

In [9]:
b.dtype

dtype('float64')

In [10]:
b.nbytes

48

In [11]:
b.size * b.itemsize

48

In [18]:
o = np.ones((5,5))
print(o)

p = np.zeros((3,3))
p[1,1] = 9
print(p)

o[1:4,1:4] = p
print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
c = np.arange(1,31)
c = c.reshape(6,5)
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [22]:
d = c[2:4, 0:2]
print(d)

e = c[[0,1,2,3],[1,2,3,4]]
print(e,'\n')

e = c[range(0,4),range(1,5)]
print(e)

d = c[[0,-2,-1], 3:]
print(d)


[[11 12]
 [16 17]]
[ 2  8 14 20] 

[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
